### PR TITLE
Render relative links in README Markdown correctly when it comes from Github, plus some URL path cleanup

### LINKED ISSUE #8: The package README renderer produces incorrect, ever-growing URLs that confuse crawlers
The README renderer is able to turn markdown links into clickable ones, but the way it does so has a few problems. The following uses the [cisagov/icsnpp-opcua-binary](https://github.com/cisagov/icsnpp-opcua-binary) package as an example, see [here](https://packages.zeek.org/packages/view/1c43296f-78de-11ec-ba82-0a598146b5c6/).

* It does not understand that the relative links relate to the site the package is hosted from, rendering it instead relative to packages.zeek.org. For example, `[opcua_binary-req_res_header_analyzer.pac](src/req-res-header/opcua_binary-req_res_header_analyzer.pac)` turns into `https://packages.zeek.org/packages/view/1c43296f-78de-11ec-ba82-0a598146b5c6/src/req-res-header/opcua_binary-req_res_header_analyzer.pac`.
* Visiting this URL does not remove the path suffix after the package hash — the live URL remains `https://packages.zeek.org/packages/view/1c43296f-78de-11ec-ba82-0a598146b5c6/src/req-res-header/opcua_binary-req_res_header_analyzer.pac`, not `https://packages.zeek.org/packages/view/1c43296f-78de-11ec-ba82-0a598146b5c6`. The content shown is just the package README again.
* Additional link visits now keep adding to the URL, growing it further.

This caused sufficient disk use on our server to fill up the disk.

The server shouldn't render these URLs local to packages.zeek.org, and it should strip suffixes after the hash if they don't relate to packages.zeek.org itself.

### PR DESCRIPTION
**Pull request by ckreibich**
Alright, I have no idea how "correct" any of this is for PHP's Cake framework, but:
* URLs with garbage after the package & tag views get redirected back to "clean" URLs
* We now correctly render README paths to Github — you can try [here](https://packages.zeek.org/packages/view/1c43296f-78de-11ec-ba82-0a598146b5c6).
* We strip links in READMEs when they're not from Github, just keeping their anchor text

This last part ignores #6 for the time being but should work correctly if and when those READMEs appear.

This is actually running now on packages.zeek.org, hopefully improving the disk-fill situation. :crossed_fingers: 

The site has a lot of problems — the whole PHP dependency thing is busted on the instance we're running the site on. The `composer` version installed is old and uses ridiculous amounts of memory during dependency resolution, while a newer version avoids that but then blows up in the actual package dependencies because we're installing one package from a version called "dev-master", which has moved on and no longer works with our Cake version. I tried a couple of things but couldn't figure it out (interestingly, this dependency management behaves almost like zkg's but fails when it would be damn handy to be able to specify a git commit has as version — hah!).

I've simply preserved the `vendor/` tree in the resulting installation, which seems to work since we're not changing anything at that level.

Really good motivation to get the new version of the site up and running!

Resolves #8.

### CODE REVIEW

File: bropkg/src/View/Helper/MarkdownCanonifierHelper.php [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+/**
+ * Markdown canonifier
+ *
+ * This massages Markdown text to make the outcome suitable for rendering
+ * on our site. The expectation is that the output is again transformed
+ * by a markdown renderer -- see Template/Packages/view.ctp.
+ */
+class MarkdownCanonifierHelper extends Helper
+{
+  /**
```
Comment (timwoj) [inline bropkg/src/View/Helper/MarkdownCanonifierHelper.php:15]: Nit: Indentation mismatch here vs the rest of the code (2 vs 4 spaces).

File: bropkg/src/View/Helper/MarkdownCanonifierHelper.php [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+          return false;
+      }
+      if (strcasecmp(parse_url($url, PHP_URL_HOST), "github.com") == 0) {
+          /* The package resides on Github. Replace relative links with a Github
+           * blob reference into the source tree. Github does the same, with one
+           * difference: Github knows the default branch, which the blob
+           * reference requires. We do not know that branch, but Github
+           * redirects an unknown branch to the default one. So we assume
+           * "main", and hope for the redirect to work out if needed.
+           */
```
Comment (timwoj) [inline bropkg/src/View/Helper/MarkdownCanonifierHelper.php:34]: This feels sorta bad, in that it could end up with broken links in the text and we wouldn't know unless someone told us. Could we make a request to https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#get-a-repository for the repo and get the `default_branch` value from that?

**Review by timwoj — CHANGES_REQUESTED** [review]

File: bropkg/src/View/Helper/MarkdownCanonifierHelper.php (hunk 1 above)
Comment (ckreibich) [reply bropkg/src/View/Helper/MarkdownCanonifierHelper.php:15]: You know, that was on purpose — the `RstMarkupHelper` class has the same and I didn't know if that's a PHP thing. Happy to change it.

File: bropkg/src/View/Helper/MarkdownCanonifierHelper.php (hunk 2 above)
Comment (ckreibich) [reply bropkg/src/View/Helper/MarkdownCanonifierHelper.php:34]: Hrrrm. I already spent way to much time on the  whole thing. Are you thinking of adding that to `bro-pkg-web-updater.php` so it's in the metadata? Seems a bit tricky to do in the webserver.

File: bropkg/src/View/Helper/MarkdownCanonifierHelper.php (hunk 1 above)
Comment (timwoj) [reply bropkg/src/View/Helper/MarkdownCanonifierHelper.php:15]: Eh, if it's consistent across the files that's fine. I don't think php cares but it's not a big deal.

File: bropkg/src/View/Helper/MarkdownCanonifierHelper.php (hunk 2 above)
Comment (timwoj) [reply bropkg/src/View/Helper/MarkdownCanonifierHelper.php:34]: > Are you thinking of adding that to bro-pkg-web-updater.php so it's in the metadata? Seems a bit tricky to do in the webserver.

Yeah, that could be doable. In that regard though, if all of the README data is stored as part of the metadata, is there any reason to do any of this in the web server? Wouldn't it be better to do it one time in the updater and store the fixed version in the metadata?

Comment (timwoj) [reply bropkg/src/View/Helper/MarkdownCanonifierHelper.php:34]: Also, I'm entirely fine with filing a ticket for that and doing it separately, as it would be a bit of rework.

**Review by timwoj — APPROVED** [review]
Approving as it fixes the problem that we're seeing. We can file an issue to move the canonifier to the update script and discuss whether that would be an improvement separately.

**Comment by ckreibich** [comment]
THANK YOU
